### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by atlarep** [tatewake/dokuwiki-plugin-backup#26]
I keep getting a this error when I try to open the backup tool.
![image](https://cloud.githubusercontent.com/assets/20726009/17419821/3e33ea3a-5a6d-11e6-946b-20a00b9a014b.png)

**Comment by tatewake** [comment]
Server config error would be my guess.

Also, if your server is running on Windows or a non-linux system… non-linux and non-BSD systems are not supported.
