### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by zounp** [tatewake/dokuwiki-plugin-backup#28]
When I do a language delete the output tells me that the languages which I want to keep are deleted.

The screenscrape:
=============
Input
Current language: en
Language(s) should be kept: en,nl
Run option: simulate only v

Results
The following language directories will be deleted.

/www/wiki/inc/lang
/www/wiki/inc/lang/nl
/www/wiki/inc/lang/en
/www/wiki/lib/plugins/config/lang
/www/wiki/lib/plugins/config/lang/nl
/www/wiki/lib/plugins/config/lang/en
/www/wiki/lib/plugins/authldap/lang
/www/wiki/lib/plugins/authldap/lang/nl
/www/wiki/lib/plugins/authldap/lang/en
/www/wiki/lib/plugins/authplain/lang
/www/wiki/lib/plugins/authplain/lang/nl
/www/wiki/lib/plugins/authplain/lang/en
/www/wiki/lib/plugins/acl/lang
/www/wiki/lib/plugins/acl/lang/nl
/www/wiki/lib/plugins/acl/lang/en
/www/wiki/lib/plugins/revert/lang
/www/wiki/lib/plugins/revert/lang/nl
=============
The same for the live version.
In reality only en and nl are kept so it works.
Every time I repat the process I get, just after finishing the previous I get the same result.

Thanks for Language delete. I like it a very much.

Regards,

Zounp

**Comment by dsp77** [comment]
Could you explain, how this is realted to the backup plugin?

**Comment by zounp** [comment]
It is not. I somehow mixed up langdelete and backup plugin.

**Comment by tatewake** [comment]
Sounds good, I'll close this ticket then.
