### ISSUE TITLE
Authentification 

### ISSUE THREAD

**Issue by willouuu** [tatewake/dokuwiki-plugin-backup#31]
Hi
The downloadable archive in media is possible without authentication and which would like to download the archive with a simple script could.

Would it be possible to put the acl on this type of files or change the permissions of the generated files?

Thank you in advance

**Comment by phy25** [comment]
Yes, just set ACL to $conf['backupnamespace'] (by default `wiki:backup`).

**Comment by willouuu** [comment]
Ha yes i understood

I put wiki:backup prohibited for all

Sorry for the inconvenience

Thank you
