### ISSUE TITLE
PHP timeout without error message

### ISSUE THREAD

**Issue by kay-jahnke** [tatewake/dokuwiki-plugin-backup#34]
Hi,

we are using the backup plugin in a dokuwiki that is run as a lab journal. This means we upload media, that is quite big.
In the last version upgrade (of the backup plugin), the backup was moved to files of type `tar.bz2` instead of the old `tar.gz`. When running `top` on the server while performing the backup, I see that the actual compression is done through php and not with command line tools, as before.

**The Error:**
For big files (>200 MB) and large file numbers (>20000) this seems to cause a timeout (speculation on my part). What I see is that I do not get any error message, but the backup is incomplete and a lot of files (not only the huge ones) are missing.

**My System (on bitnami Docker container in Google Cloud):**
anon_id	32b2fcba28a1156dc62c79aee334b0d7
version	Release 2018-04-22a "Greebo"
popversion	2015-07-15
language	en
now	1544539768
popauto	0
conf_useacl	1
conf_authtype	authplain
conf_template	dokuwiki
page_count	1389
page_size	2404213
page_biggest	120343
page_smallest	4
page_nscount	374
page_nsnest	5
page_avg	1730.8948884089
page_oldest	1509725751
media_count	7295
media_size	19755562204
media_biggest	4260755650
media_smallest	427
media_nscount	483
media_nsnest	6
media_avg	2708096.2582591
cache_count	20436
cache_size	1555167799
cache_biggest	22132791
cache_smallest	0
cache_avg	76099.422538657
index_count	91
index_size	2287808
index_biggest	732655
index_smallest	5
index_avg	25140.747252747
meta_count	4648
meta_size	4343113
meta_biggest	8422
meta_smallest	27
meta_avg	934.40469018933
attic_count	12677
attic_size	8459977
attic_biggest	9393
attic_smallest	30
attic_avg	667.34850516684
attic_oldest	1503522219
user_count	20
edits_per_day	54.079858397996
plugin	fastwiki
plugin	pagelist
plugin	yearbox
plugin	styling
plugin	fontcolor
plugin	authad
plugin	filelisting
plugin	usermanager
plugin	dropfiles
plugin	comment
plugin	dayscroll
plugin	dw2pdf
plugin	authpdo
plugin	upgrade
plugin	mathjax
plugin	smtp
plugin	templatepagename
plugin	revert
plugin	config
plugin	safefnrecode
plugin	authplain
plugin	authldap
plugin	info
plugin	docnavigation
plugin	authpgsql
plugin	imgpaste
plugin	acl
plugin	move
plugin	authmysql
plugin	backup
plugin	extension
plugin	popularity
plugin	tag
plugin	edittable
plugin	cookielaw
plugin	dir
plugin	imagebox
pcre_version	8.38 2015-11-23
pcre_backtrack	20971520
pcre_recursion	100000
os	Linux
webserver	Apache
php_version	7.0.24
php_sapi	fpm-fcgi
php_memory	134217728
php_exectime	120
php_extension	Core
php_extension	date
php_extension	libxml
php_extension	openssl
php_extension	pcre
php_extension	sqlite3
php_extension	zlib
php_extension	bcmath
php_extension	bz2
php_extension	calendar
php_extension	ctype
php_extension	curl
php_extension	dom
php_extension	hash
php_extension	fileinfo
php_extension	filter
php_extension	ftp
php_extension	gd
php_extension	gettext
php_extension	gmp
php_extension	SPL
php_extension	iconv
php_extension	session
php_extension	intl
php_extension	json
php_extension	ldap
php_extension	mbstring
php_extension	mcrypt
php_extension	standard
php_extension	mysqlnd
php_extension	pcntl
php_extension	mysqli
php_extension	PDO
php_extension	pdo_mysql
php_extension	pdo_sqlite
php_extension	Phar
php_extension	posix
php_extension	readline
php_extension	Reflection
php_extension	imap
php_extension	SimpleXML
php_extension	soap
php_extension	sockets
php_extension	exif
php_extension	tidy
php_extension	tokenizer
php_extension	xml
php_extension	xmlreader
php_extension	xmlrpc
php_extension	xmlwriter
php_extension	xsl
php_extension	zip
php_extension	cgi-fcgi
php_extension	Zend OPcache

**Comment by kay-jahnke** [comment]
Just looking through the old issues, maybe this is related to #30, as my file size of the backup is 3,24 GB which is close to the 3,2 GB reported in that issue.

**Comment by tatewake** [comment]
@kay-jahnke If we are seeing timeouts (I'll assume this is the case), it's likely due to two things…

1. Large amount of data in your wiki, which could potentially time regardless of solution…
2. The refactor using an internal PHP library for tarring / compression rather than "shell executing" compression tools, which will likely be slower than the previous solution, but is more portable across systems and probably "safer"

I think it might be useful to re-enable the "shell execution" code that was previously in play (not necessarily to solve your issue, but to provide a fallback option.)

I am curious of two things…

1. Do the backup files actually get created if you wait long enough?
2. Also, if the backup file exists, can you ensure that the archives are valid? (Run something like `tar -tzf my_tar.tar.gz >/dev/null`)

The answers to these questions I hope will help better organize a fix if one can be made.

Thanks in advance.

**Comment by kay-jahnke** [comment]
Digging deeper into the problem it turned out that the disk space was the actual problem.
As I was deleting old backups afterwards, new space freed up and the backup went through fine.

Thanks for the answer anyhow.
