### ISSUE TITLE
Backup failed. Could not open file for reading

### ISSUE THREAD

**Issue by LuanLucasTS** [tatewake/dokuwiki-plugin-backup#36]
I switched from linux server to windows and when I try to backup this error appears:
Backup failed. Could not open file for reading
what do I do?

**Comment by tatewake** [comment]
Hi @LuanLucasTS ,

BackupTool requires both `tar` and either `gzip` or `bzip2` to be available on your system. In linux and any variation of BSD (like macOS), these tools are typically available by default.

On Windows, these tools aren't available by default.

That said, you can get BackupTool to run under Windows if you do the following:

* Install tar and gzip (or tar, gzip, and bz2) via [Cygwin](http://cygwin.com/) for Windows and make it available to the server.
* Or you can install [Pear](http://pear.php.net/) for your PHP installation.

Personally I recommend either switching back to hosting this on Linux, or possibly Linux within a Virtual Machine such as VirtualBox, if possible.

**Comment by LuanLucasTS** [comment]
Thank you. I'll try.

**Comment by LuanLucasTS** [comment]
Unfortunately it didn't work. I installed cygwin with all packages then installed tar and gzip separately but the error still persists. It stops at the folder "data / pages /"

**Comment by tatewake** [comment]
Hi @LuanLucasTS ; I would suggest installing Pear (as stated above) if your initial attempt at installing tar and gzip separately didn't work.

If this still doesn't work, I would really suggest moving your server to Linux or Linux inside of a Virtual Machine such as VirtualBox, as Linux is just better suited for severs in general.
