### ISSUE TITLE
Admin Panel broken on "Frusterick Manners"

### ISSUE THREAD

**Issue by Mathilu** [tatewake/dokuwiki-plugin-backup#37]
I've the same problem as described in this closed issue 33: https://github.com/tatewake/dokuwiki-plugin-backup/issues/33

But I'm not able to upgrade to the latest version of DokuWiki, as I need to switch to a new Linux Distribution I have to backup and restore my data. (because of PHP)
Is there at least an option to downgrade the backup plugin to an older version?

**Comment by phy25** [comment]
You can probably downgrade manually using Git logs?

**Comment by phy25** [comment]
You can probably downgrade manually using Git logs?

**Comment by tatewake** [comment]
Hi @Mathilu ; I can only really provide support for current released versions of DokuWiki.

Generally, I don't think DokuWiki can support downloading older versions of plugins like BackupTool on its own.

You would probably have to "clone" this repo in the location where the plugin is supposed to be located inside of DokuWiki.

You could then do a `git log` on the file `plugin.info.txt`, and choose which commit to use, as that file change corresponds with a new version of the plugin.

That said, if you're unable to do this… I would suggest (when it comes time to upgrade your Linux distribution), to `tar` and `gzip` your entire DokuWiki installation as a temporary measure.

Hope that helps.
