### ISSUE TITLE
Text "The backup tool is working, please wait" keeps being displayed at the top

### ISSUE THREAD

**Issue by Stan-librarian** [tatewake/dokuwiki-plugin-backup#39]
Hello,

This is a nice plugin, even though I didn't test the restoration of the backup. 

I just tried to backup my dokuwiki, it works great, the file is generated, but even though it is displaying "Backup successful. Download wiki:backup:dw-backup-20200627-112317.tar.bz2." at the bottom of the page, it is still displaying "The backup tool is working, please wait" at the top. Strange, isn't it?

My browser is Firefox 77.0.1 64 bits with some security extensions (HTTPS Everywhere, ClearURLs, uBlock Origin…)

**Comment by KillerSenf** [comment]
Same issue here, FF 78.0.2 64bit (Windows).

**Comment by tatewake** [comment]
Hello @Stan-librarian and @KillerSenf ; this issue has been resolved as of the latest release.
You can update the BackupTool plugin from within the extension manager to see the result.

Best regards,
--Terence
