### ISSUE TITLE
Backup failed. Could not open file for reading: D:/CFI Wiki/DokuWikiStick/dokuwiki/data/pages/XXXXX

### ISSUE THREAD

**Issue by Anonymous215025** [tatewake/dokuwiki-plugin-backup#40]
I am using DokuWikiStick and have the files on a flash drive. I am the only user and the account is most definitely admin; using the backup tool and pressing create backup gives me the above error:

> Backup failed. Could not open file for reading: D:/CFI Wiki/DokuWikiStick/dokuwiki/data/pages/XXXXX

I am on rc-2020-06-09 "Hogfather" RC3.

**Comment by tatewake** [comment]
Hi @Anonymous215025 ,

BackupTool requires both `tar` and either `gzip` or `bzip2` to be available on your system. In linux and any variation of BSD (like macOS), these tools are typically available by default.

On Windows, these tools aren't available by default.

That said, you can get BackupTool to run under Windows if you do the following:

* Install tar and gzip (or tar, gzip, and bz2) via [Cygwin](http://cygwin.com/) for Windows and make it available to the server.
* Or you can install [Pear](http://pear.php.net/) for your PHP installation.

Personally I recommend either switching back to hosting this on Linux, or possibly Linux within a Virtual Machine such as VirtualBox, if possible.

**Comment by Anonymous215025** [comment]
Ah, gotcha. Thank you very much for helping me diagnose the problem and providing a solution!
