### ISSUE TITLE
Fatal error - Uncaught splitbrain\PHPArchive\ArchiveCorruptedException

### ISSUE THREAD

**Issue by bigfox** [tatewake/dokuwiki-plugin-backup#43]
Hi @tatewake, at first ... great job and thanks for this plugin.

I try this plugin, but I get the following error after click [Create Backup]:

```
Fatal error:  Uncaught splitbrain\PHPArchive\ArchiveCorruptedException: The size of /data/www/22565/bigfox_net/www/wiki/data/pages/projekty changed while reading, archive corrupted. read 3 expected 0 in /data/www/22565/bigfox_net/www/wiki/vendor/splitbrain/php-archive/src/Tar.php:285
Stack trace:
#0 /data/www/22565/bigfox_net/www/wiki/lib/plugins/backup/admin.php(334): splitbrain\PHPArchive\Tar-&gt;addFile('/data/www/22565...', Object(splitbrain\PHPArchive\FileInfo))
#1 /data/www/22565/bigfox_net/www/wiki/lib/plugins/backup/admin.php(414): admin_plugin_backup-&gt;addDirectoryToTar(Object(splitbrain\PHPArchive\Tar), '/data/www/22565...', 'data/pages', Array)
#2 /data/www/22565/bigfox_net/www/wiki/lib/plugins/backup/admin.php(293): admin_plugin_backup-&gt;backupPages(Object(splitbrain\PHPArchive\Tar), Array)
#3 /data/www/22565/bigfox_net/www/wiki/lib/plugins/backup/admin.php(154): admin_plugin_backup-&gt;createBackup('/data/www/22565...', Array, Array)
#4 /data/www/22565/bigfox_net/www/wiki/lib/plugins/backup/admin.php(58): admin_plugin in /data/www/22565/bigfox_net/www/wiki/vendor/splitbrain/php-archive/src/Tar.php on line 285
```

Path `data/pages/projekty` is folder, not file.

Dokuwiki version: `Release 2020-07-29 "Hogfather"`
Plugin version: `2020-10-21`

Thank you in advance for your reply

**Comment by tatewake** [comment]
Hi @bigfox ,

Thank you for using the plugin.

I believe what we're seeing here is a file or directory within that "projekty" directory being changed / added / removed while the backup plugin is running.

I'm guessing one of the following might be the case:

If we believe the error message:

* Yourself / another user adding / editing / deleting a page while the backup is running
* Some plug-in writing to page data or dynamically generating pages during the backup (for instance, the referrers plugin could do this)
* Some outside process writing to that directory or a sub-directory

If we don't believe the error message:

* Possibly out of hard drive space or running out of RAM during a backup?
* Possibly an issue with permissions where the plugin can't actually read the directory or a sub-directory inside of it?

Can you investigate and see if any of these issues exist?

(Also, I assume you're running the server on Linux, or are you running on Windows?)

**Comment by tatewake** [comment]
Also, I'd be curious if you're able to run:

`tar cfv test.tar projekty` on your server from within SSH.

I suspect if you're running this on a university server within an enforced storage limit or something, this could also cause issues.

**Comment by bigfox** [comment]
I do some investigation:


> * Yourself / another user adding / editing / deleting a page while the backup is running

No, my dokuwiki instance is my personal wiki, so myself only

> * Some plug-in writing to page data or dynamically generating pages during the backup (for instance, the referrers plugin could do this)

Not found some suspicious plugin

> * Some outside process writing to that directory or a sub-directory
> * Possibly out of hard drive space or running out of RAM during a backup?
> * Possibly an issue with permissions where the plugin can't actually read the directory or a sub-directory inside of it?

Dokuwiki instance works fine ... editing pages, upload media ... but when running backup error occurred

**Comment by bigfox** [comment]
I didn't mentioned, when run backup, TAR file was created and the some files were backed up to it.

But error happened when reach subdirectory ... I tried separate backups type (pages only, conf only, template only) ... same error if exist some subdirectory.

So i used my little knowledge of PHP and try exclude subdirectries ... and it works! :)

I make "fix" in `admin.php`, function `addDirectoryToTar`, add code below into foreach loop
```php
if (is_dir($path)) {
    continue;
}
```

I guess I make it as PR and send it to you.

**Comment by tatewake** [comment]
Hi @bigfox ,

The backup plugin is supposed to be able to read subdirectories and back them up as well.

I personally have never had an issue backing up subdirectories, and I believe since the last major redesign of the plugin (about three years ago), there's been no reports like yours (and there are many users of this plugin), so…

…I believe there is some directory permission issues in your local install.

I would recommend that you validate your setup with Dokuwiki's ideal permission setup:
 * https://www.dokuwiki.org/install:permissions

(However, this is totally up to you if you want to do so.)

If you believe that your patch / PR works better for your use case, that's okay, and by all means continue to use that patch, but I don't think I would accept that as a change to the project, as I think it will not be correct for the majority of users.

Thank you!

**Comment by bigfox** [comment]
Hi @tatewake, ok, no problem ;-)
