### ISSUE TITLE
No components for backup

### ISSUE THREAD

**Issue by mmilinovsky** [tatewake/dokuwiki-plugin-backup#45]
Backup worked like a charm since some days ago, but now I see no components to select for backup on the admin-page. Deinstalled und reinstalled BackupTool - no change :-(

I use dokuWiki Release 2020-07-29 "Hogfather", BackupTool for DokuWiki 1.0.1

Any ideas what goes wrong or what I could check?

**Comment by tatewake** [comment]
Hi @mmilinovsky ,

Two things to check:

1. If you're running the server on Windows, there's an "agree" button you must press to show the components for backup.
2. It's possible there's another plugin that is conflicting somehow which may make the page fail to render. You can disable other plugins through the "Extension Manager" and see if reloading the backup admin-page starts working again.

Please check these two, and let me know what you discover.

Thank you.

**Comment by mmilinovsky** [comment]
Hi Terence,

thank you for your fast response! My dokuWiki is running on Linux (Ubuntu Server 20.04.1 LTS), so I didn't notice any "agree"-button. I disabled all plugins that could be disabled (some can't like Configuration Manager, ACL Manager etc.), but the backup admin-page did not show any components to backup. I even restarted the server but the situation did not change.

Any further ideas?

Regards,
	Martin

**Comment by mmilinovsky** [comment]
Hi Terence,

posssibly another hint: I remember that the filesystem, on which the backups are stored, ran full some days ago. I deleted manually some of the backups on the commandline, but this should not affect the backuptool, should it?

Regards,
Martin

**Comment by tatewake** [comment]
Hi @mmilinovsky ,

Backups are stored to… I believe inside the media directory under `:wiki:backup`.

If you have full disk, it will likely not be able to contain new backups. You will probably need at least twice the size of a backup file to properly create one.

I would suggest investigating:

1. How much free space your disk has left
2. If your "wiki/backup" directory is writeable inside of the "media" directory
3. If in "configuration", what value the "media" directory is set to

I suspect what you're seeing isn't necessarily an issue with the BackupTool plugin, but perhaps an issue with your filesystem or how your configuration is set.
