### ISSUE TITLE
backup failing on conf

### ISSUE THREAD

**Issue by alimat-nz** [tatewake/dokuwiki-plugin-backup#46]
I installed the backup plugin today and tested it. Works well for most folders, but is consistently failing when conf is selected. the screen stops updating having displayed conf/en. whether i leave it there until i gte logged out of DW or if i jump to another page at that point the backup file is always 4.1K. 

Any Ideas?

**Comment by tatewake** [comment]
Hi @alimat-nz ; sorry I didn't respond to your issue from a few months ago.

This sounds like an "access permission" (or "file permission") issue.

Please review the following to set up correct file permissions for your DokuWiki instance:

* https://www.dokuwiki.org/install:permissions

Thanks!
